import { SiteHeader } from "../components/site-header";
import { SiteFooter } from "../components/site-footer";
import { site } from "../lib/seo";

const seo = site.page({
  title: "Terms of Use",
  path: "/terms",
  description:
    "How you may use the Lacspace templates and the apps generated by create-lacspace-app — licensing, permitted use, and the terms for the live demos at templates.lacspace.com.",
});
export const metadata = seo.metadata;

const UPDATED = "September 5, 2026";

export default function Terms() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(seo.jsonLd) }}
      />
      <div className="aurora" />
      <SiteHeader />
      <main className="wrap">
        <section className="sec" style={{ paddingTop: 56 }}>
          <div className="sec-head">
            <div className="eyebrow">Legal</div>
            <h2>Terms of Use</h2>
            <p>
              These terms cover the Lacspace templates, the apps you generate
              with <span className="mono">create-lacspace-app</span>, and the live
              demos hosted at <span className="mono">templates.lacspace.com</span>.
              Last updated {UPDATED}.
            </p>
          </div>

          <div className="hb-body" style={{ maxWidth: 820 }}>
            <div className="callout">
              <strong>In one line:</strong> the apps you scaffold are entirely
              yours to use, ship and sell — for free, in personal and commercial
              projects — under the Lacspace Free Licence. The live demos on this
              site are for evaluation, not for copying wholesale as a hosting
              service.
            </div>

            <h2 id="license">1. Licence</h2>
            <p>
              The templates and the code emitted by{" "}
              <span className="mono">create-lacspace-app</span>, together with the{" "}
              <span className="mono">@lacspace/*</span> packages they depend on,
              are provided under the{" "}
              <a
                className="link"
                href="https://lacspace.com/licenses/lacspace-free-1.0"
                target="_blank"
                rel="noopener"
              >
                Lacspace Free Licence v1.0
              </a>{" "}
              — a permissive, free-to-use licence. Subject to that licence you
              may use, copy, modify, merge, publish, distribute and sell the
              generated apps at no cost.
            </p>

            <h2 id="your-apps">2. The apps you generate are yours</h2>
            <p>
              When you run the CLI, the output is your project. You own the code
              you generate and everything you build on top of it. You are not
              required to credit Lacspace, pay a fee, or share your source. You
              are responsible for the content, data and services you add.
            </p>

            <h2 id="demos">3. The live demos</h2>
            <p>
              The eight demos linked from this gallery are hosted for evaluation
              so you can see what the templates produce before you install
              anything. You may browse and inspect them freely. You may not:
            </p>
            <ul>
              <li>
                rehost or mirror these demos as your own product or hosting
                service;
              </li>
              <li>
                present them, or Lacspace, in a misleading way or imply an
                endorsement that does not exist;
              </li>
              <li>
                scrape, stress-test, or attempt to disrupt the demo deployments.
              </li>
            </ul>
            <p>
              The demos use placeholder brand names (“Acme Studio”, “Olive &amp;
              Ember”, and similar) purely as sample content. They are fictional
              and imply no association with any real business.
            </p>

            <h2 id="trademarks">4. Names &amp; trademarks</h2>
            <p>
              “Lacspace”, the Lacspace mark and logo are trademarks of Lacspace.
              The permissive code licence does not grant rights to use these
              marks. You may state, factually, that your app was built with
              create-lacspace-app.
            </p>

            <h2 id="thirdparty">5. Third-party services</h2>
            <p>
              A generated app is a plain Next.js application. If you connect it to
              third-party services (hosting, analytics, payments, email and so
              on), your use of those services is governed by their own terms, not
              these.
            </p>

            <h2 id="warranty">6. No warranty</h2>
            <p>
              The templates, generated code and demos are provided “as is”,
              without warranty of any kind, express or implied. To the maximum
              extent permitted by law, Lacspace is not liable for any damages
              arising from their use. You are responsible for reviewing and
              testing generated code before deploying it to production.
            </p>

            <h2 id="changes">7. Changes</h2>
            <p>
              We may update these terms as the templates evolve. Material changes
              will be reflected by the “last updated” date above. The licence that
              applies to a given release of the packages is the one stated in that
              release.
            </p>

            <h2 id="contact">8. Contact</h2>
            <p>
              Questions about these terms or the licence?{" "}
              <a className="link" href="https://lacspace.com" target="_blank" rel="noopener">
                lacspace.com
              </a>{" "}
              — or open an issue on{" "}
              <a
                className="link"
                href="https://github.com/lacspace/npm-packages"
                target="_blank"
                rel="noopener"
              >
                GitHub
              </a>
              .
            </p>
          </div>
        </section>
      </main>
      <SiteFooter />
    </>
  );
}
